version: 2

updates:
  - package-ecosystem: poetry
    assignees: "alexander-sidorov"
    directory: "/"
    schedule:
      day: "monday"
      interval: "weekly"
      time: "06:00"
    labels:
      - "auto: dependencies"
    reviewers:
      - "alexander-sidorov"
      - "karmaxa"
      - "Mikhailiuk-Dmitriy"
